package updater

// appID from equinox
const appID = "app_4SbsY14WUcg"

// public portion of signing key generated by `equinox genkey`
var publicKey = []byte(`
-----BEGIN ECDSA PUBLIC KEY-----
MHYwEAYHKoZIzj0CAQYFK4EEACIDYgAEGj6kWvbx0d2YcEmM2KijWSnTenwsSB22
/AH1+uK39i6Jr4mfIN20WR1+w2jtxCnmqiz0yiomSJA5TxJ9mbyp/G0o3/0Rt/Yq
3F9GZBmWbduYawWwP5pgPduPWZlTDf7Q
-----END ECDSA PUBLIC KEY-----
`)
